// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mnozenie;

namespace mnozenie.Migrations
{
    [DbContext(typeof(WynikiA))]
    partial class WynikiAModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("mnozenie.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("GradeValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numberofex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ocena")
                        .HasColumnType("TEXT");

                    b.HasKey("GradeId");

                    b.ToTable("Wyniki");
                });
#pragma warning restore 612, 618
        }
    }
}
